[package]
name = "ngrok"
version = "0.1.0"
authors = ["nkconnor <ngrok@nconnor.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.10.8", features = ["blocking", "json"] }
url = {version="2.2.0", features=["serde"]}
thiserror = "1.0"
serde_json = "1"
serde = { version = "1", features =["derive"] }
