name: tests 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run tests
      run: >
            wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip &&
            unzip ./ngrok-stable-linux-amd64.zip &&
            echo "$PWD/ngrok" >> $GITHUB_PATH &&
            cargo test --verbose -- --test-threads=1
